### PR TITLE
added serializers for Websites and Users, and a GET in usersRouter.js

### PR DESCRIPTION
**Pull request by RipNasty**
As the title says!

Adding the GET request in usersRouter.js was to display our Users.

### CODE REVIEW

**Comment by RipNasty** [comment]
https://www.loom.com/share/2c31c88043304bb0acb26ec72f5ca222

**Comment by therese28** [comment]
Looks good!

**Comment by AngeC22** [comment]
nice

**Comment by Chepenik** [comment]
Great job with serializers. Will need to add a serializer for image URL in future, but I need to commit what I've been working on before we can do that so this looks great

**Pull request merged**
